# Mostly copied from https://github.com/onnx/onnx/blob/main/.github/workflows/dco_merge_group.yml
# Because of https://github.com/dcoapp/app/issues/199

name: DCO
on:
  merge_group:

permissions:
  contents: read

jobs:
  DCO:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - run: echo "dummy DCO workflow (it won't run any check actually) to trigger by merge_group in order to enable merge queue"
