name: check-licenses

on: [push, pull_request]

permissions:
  contents: read

jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
    - uses: EmbarkStudios/cargo-deny-action@2d8c9929d8f9f42bedba73f1287cb0b479f07acb
      with:
        command: check bans licenses
