name: ts-build

on:
  workflow_call: {}

env:
  TURBO_CACHE_DIR: ./.turbo/cache
  TURBO_TELEMETRY_DISABLED: true
  TURBO_RUN_SUMMARY: true

defaults:
  run:
    working-directory: ./typescript

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

      - name: Setup
        uses: ./.github/actions/ts-setup
        with:
          working-directory: ./typescript

      - name: Build
        run: yarn turbo build

      - name: Upload Build
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: build-assets
          path: 
            ./typescript/**/dist/