name: ts-release (@wasmcloud/lattice-client-core)

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  release:
    name: '@wasmcloud/lattice-client-core'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: typescript/packages/lattice-client-core

    steps:
      - name: Checkout
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

      - name: Extract Tag Info
        id: extract
        uses: release-kit/semver@97491c46500b6e758ced599794164a234b8aa08c
        with:
          # Matches the following patterns:
          # - path pattern: `path/to/project/v1.2.3`
          # - package pattern: `refs/tags/package-name-v1.2.3`
          # - tag only pattern: `refs/tags/v1.2.3`
          pattern: '^(?:.*\/|[a-z-]*)?v?(.*)$'

      - name: Setup
        uses: ./.github/actions/ts-setup
        with:
          working-directory: ./typescript

      - name: Publish package
        run: yarn npm publish --provenance --access public --tag ${{ steps.extract.outputs.prerelease == '' && 'latest' || 'next' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}